name: Docker Build Image

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
         docker build . --file Dockerfile --tag ${{ inputs.image_name }}:${{ input.image_tag }}

        
