name: Docker Build Image

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      dockerfile_path:
        required: false
        type: string
        default: ./Dockerfile
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
         docker build . --file Dockerfile --tag ${{ inputs.image_name }}:$(git rev-parse --short HEAD)

        
